[project]
name = "mcp-sysinfo"
version = "0.1.0"
description = "Simple mcp server to view system information"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.5.0",
]
